- job:
    name: zuul-preview-distcheck
    parent: unittests
    description: |
      Run make distcheck on zuul-preview

- project:
    check:
      jobs:
        - zuul-preview-distcheck
    gate:
      jobs:
        - zuul-preview-distcheck
