- hosts: all
  tasks:

    - name: Run make distcheck
      shell:
        executable: /bin/bash
        chdir: '{{ zuul_work_dir|default(zuul.project.src_dir) }}'
        cmd: |
          set -ex
          ./bootstrap.sh
          ./configure
          make
          make distcheck
